server:
  port: 80

spring:
  application:
    name: springcloud-order-hystrix

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

# 在Feign中开启Hystrix
feign:
  hystrix:
    enabled: true