server:
  port: 9001

spring:
  application:
    name: payment-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露需要监控的内容