#8001表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8001

#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: springcloud-payment
  cloud:
    zookeeper:
      connect-string: 192.168.2.202:2181