server:
  port: 80

spring:
  application:
    name: order-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  nacos-user-service: http://payment-nacos #消费者将要去访问的微服务名称（注册成功进Nacos的微服务提供者）