server:
  port: 9527

spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能 利用微服务名进行路由
      routes:
        - id: payment_routh #路由ID 没有固定规则但要求唯一 建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://springcloud-payment #匹配后提供服务的动态路由地址 代替写死的地址
          predicates:
            - Path=/payment/get/** #断言 路径相匹配的进行路由

        - id: payment_routh2 #路由ID 没有固定规则但要求唯一 建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://springcloud-payment #匹配后提供服务的动态路由地址 代替写死的地址
          predicates:
            - Path=/payment/lb/** #断言 路径相匹配的进行路由
#            - After=2020-06-03T14:25:39.554+08:00[Asia/Shanghai]
#            - Before=2020-06-03T14:25:39.554+08:00[Asia/Shanghai]
#            - Between=2020-06-03T14:25:39.554+08:00[Asia/Shanghai],2020-06-03T14:25:39.554+08:00[Asia/Shanghai]
#            - Cookie=username,py #请求要携带Cookie username=py
#            - Header=X-Request-Id, \d+ #请求头要带有X-Request-Id属性并且值为整数的正则表达式 X-Request-Id:123
#            - Host=**.baidu.com #请求头中必须含有baidu.com
#            - Method=GET #请求方式为GET才能访问
#            - Query=username, \d+ #需要有参数名username并且值必须是整数才能路由 username=1

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    hostname: springcloud-gateway-service